#%RAML 0.8
---
title: REST
baseUri: http://{host}/api/{version}
version: v1
#uriParameters:
#  host:
#    description: The host of the API (e.g., 'localhost')
#    displayName: Host
#    type: string
#  port:
#    description: The port on the host where the API is served (e.g., 8080)
#    displayName: Port
#    type: number

schemas:
  - instance: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type": "object",
        "properties": {
          "parameters": {
            "type": "object",
            "properties": {
              "invoker_config": {}
            }
          },
          "results": {
            "type": "object",
            "properties": {
              "stdout": { "type": "string" },
              "stderr": { "type": "string" }
            }
          },
          "_links": {
            "type": "object",
            "patternProperties": {
              "[a-zA-Z0-9-_.]+": {
                "type": "object",
                "properties": {
                  "href": { "type": "string" }
                }
              }
            }
          },
          "_id": { "type": "string" },
          "status": { "type": "string" },
          "created": { "type": "string" },
          "finished": { "type": "string" },
          "failed": { "type": "string" },
          "error": { "type": "string" }
        },
        "required": [ "parameters" ]
      }
  - instanceCollection: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type": "array",
        "description": "List of instances"
      }


/instances:
  get:
    description: List all instances
    queryParameters:
      status:
        type: string
        description: Filter instances by status ('running', 'finished', etc.)
        example: running
        required: false
    responses:
      200:
        body:
          application/json:
            schema: instanceCollection
  post:
    description: Add a new instance
    body:
      application/json:
        schema: instance
    responses:
      201:
        body:
          application/json:
            schema: instance
  /{instanceId}:
    get:
      description: Get instance details
      responses:
        200:
          body:
            application/json:
              schema: instance
        404:
          body:
            application/json:
              example: |
                { "message": "instance missing" }
    put:
      description: Update instance to set status, e.g., to 'running'
      body:
        application/json:
          schema: instance
          example: |
            { "status": "running" }
      responses:
        200:
          body:
            application/json:
              schema: instance
    delete:
      description: Delete instance permanently
